name: CI Pipeline for Spring Boot with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: {{javaVersion}}
  WORKING_DIR: {{workingDirectory}}

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ${{ env.WORKING_DIR }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.JAVA_VERSION }}-${{ hashFiles('**/${{ env.WORKING_DIR }}/*.gradle*', '**/${{ env.WORKING_DIR }}/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.JAVA_VERSION }}-
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew clean test
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build application
        run: ./gradlew build -x test
        working-directory: ${{ env.WORKING_DIR }}
